import type { CharacterPoseSettings } from '../types';

export const BATMAN_POSE: CharacterPoseSettings = {
    leftArmX: -8,
    leftArmY: -18,
    leftArmZ: 7,
    leftElbowX: -6,
    leftElbowY: 23,
    leftElbowZ: 24,
    rightArmX: 4,
    rightArmY: 23,
    rightArmZ: 5,
    rightElbowX: 17,
    rightElbowY: -14,
    rightElbowZ: 28,
    leftLegX: -4,
    leftLegY: -8,
    leftLegZ: 0,
    leftKneeX: 0,
    leftKneeY: -14,
    leftKneeZ: 0,
    rightLegX: 0,
    rightLegY: 0,
    rightLegZ: 0,
    rightKneeX: 0,
    rightKneeY: 0,
    rightKneeZ: 0,
    modelScale: 1.54,
};
